# The root of your project (where go.mod lives)
root = "."

tmp_dir = "tmp"

[build]
  # This is the final binary that Air will run
  bin = "tmp/server"

  # This is the build command (from project root)
  cmd = "go build -o tmp/server ./cmd/server"

  # Delay before rebuilding
  delay = 1000

  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]

  log = "build-errors.log"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false
